#!/usr/bin/env node
const program = require('commander');

program
  .version('0.0.1')
  .command('ideogram', 'Create a ideogram to pinyin database');

program
  .version('0.0.1')
  .command('unihan-load', 'Unihan load');

program
  .version('0.0.1')
  .command('cc-ce-dict-load', 'CC CE Dict load');

program
  .version('0.0.1')
  .command('3lines-load', '3 Lines load');

program.parse(process.argv);
