#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
find="console"
replace=""
BASEDIR=${BASEDIR//$find/$replace}
NODE_PATH="/usr/local/bin/node"
export CMD="${NODE_PATH} --expose-gc --max_old_space_size=4096 ${BASEDIR}command/console.js $1 $2 $3 $4"
$CMD
