#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
find="console"
replace=""
BASEDIR=${BASEDIR//$find/$replace}
export CMD="${BASEDIR}command/console.js $1 $2 $3 $4"
$CMD